#!/bin/bash
set -e
/sbin/my_init &

# Run Mongo configuration
cd /configuration/playbooks && \
    ansible-playbook run_role.yml -i localhost, -c local \
        -e role=mongo \
        -e@/tmp/server-vars.yml

# Import Appsembler demo course
rm -rf /edx/var/edxapp/data/
cd /configuration/playbooks && \
    ansible-playbook run_role.yml -i localhost, -c local \
        -e role=demo \
        -e demo_course_id=Appsembler/TEST205/course \
        -e demo_code_dir=/edx/app/demo/appsembler-demo-course \
        -e demo_repo=https://github.com/emrob/demo-course \
