#!/bin/sh
set -e
cd /var/tmp/configuration/playbooks && \
    ansible-playbook run_role.yml -i localhost, -c local -e role=rabbitmq_configure
sleep infinity  # Sleep forever so runit doesn't restart this script
